# Generated by Django 3.1.4 on 2021-01-03 20:32

from django.db import migrations, models
import extensions.validator_files


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_auto_20210103_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar', verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000, verbose_name='درباره من'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='brith_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='resume_file',
            field=models.FileField(help_text='پسوند فایل فقط باید شامل نوع pdf و یا  word باشد', null=True, upload_to='resumeFile', validators=[extensions.validator_files.validate_file_extension], verbose_name='فایل رزومه'),
        ),
    ]
