# Generated by Django 3.1.4 on 2021-01-04 06:16

from django.db import migrations, models
import django.utils.timezone
import extensions.customFieldTypes


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_auto_20210104_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='blog')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coding_skills',
            options={'verbose_name': 'مهارت های کدنویسی', 'verbose_name_plural': 'مهارت های کدنویسی'},
        ),
        migrations.AlterModelOptions(
            name='design_skills',
            options={'verbose_name': 'مهارت های طراحی', 'verbose_name_plural': 'مهارت های طراحی'},
        ),
        migrations.AlterModelOptions(
            name='educations',
            options={'verbose_name': 'تحصیلات', 'verbose_name_plural': 'تحصیلات'},
        ),
        migrations.AlterModelOptions(
            name='experiences',
            options={'verbose_name': 'تجربیات', 'verbose_name_plural': 'تجربیات'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'کارهایی که انجام میدهم'},
        ),
        migrations.AlterField(
            model_name='coding_skills',
            name='percent',
            field=extensions.customFieldTypes.IntegerRangeField(help_text='میزان درجه مهارت شما از 1 الی 100', verbose_name='میزان مهارت (به درصد)'),
        ),
        migrations.AlterField(
            model_name='coding_skills',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='date_of_date',
            field=models.CharField(max_length=15, verbose_name='از تاریخ تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='date_of_date',
            field=models.CharField(max_length=15, verbose_name='از تاریخ تا تاریخ'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='experiences',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='services',
            name='icons',
            field=models.ImageField(upload_to='myicons', verbose_name='آیکن'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
