# Generated by Django 3.1.4 on 2021-01-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0006_auto_20210104_0946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
